### ISSUE TITLE
Project Review

### ISSUE THREAD

**Issue by acatejr** [cloudmesh-community/hid-sp18-505#16]
I am hoping you will look at the work so far and provide feedback.  I am particularly wondering about how to make this a big-data worthy project.

**Comment by acatejr** [comment]
Any thoughts yet?

**Comment by laszewsk** [comment]
can you provide concrete urls for review

**Comment by acatejr** [comment]
I had to run some chores after I made my last comment.  While running chores, I had an [epiphany](https://gph.is/2nsSHCz).  So please disregard this ticket, and the associated comments.  I am going to work on my epiphany now and then run that by you in a few days.
