### ISSUE TITLE
Explore graphql and github/gitnub issues

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/hid-sp18-505#23]
graphql & github
can you try to see to get some examples with github and graphql, could you see if you can get info for github issues

NOt sure if that works

 

https://developer.github.com/v3/#graphql-global-relay-ids

**Comment by acatejr** [comment]
@laszewsk  Would this be a possible use case?  Use python to access GitHub's API and read the issues for a project, then display them or do something with them?  GitHub's API is GraphQL based so this would be an interesting client use of graphql.

**Comment by acatejr** [comment]
@laszewsk I hope you are getting ready to take some time off next week.  I am not sure if you saw the mention in one of my latest code commits, but I have integrated a call to GitHub's graphql API that retrieves the number of issues in a repository.  The repository has to be open to the public.  I am going to begin making a tutorial about this.  I will run more ideas by you on piazza.
