### ISSUE TITLE
module

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/hid-sp18-505#24]
create folder called cloudmesh/graphql

move all source code but not requirements.txt into that

**Comment by laszewsk** [comment]
i created dir and setup.py, modify setup.py, but keep dunamic name space.

move code to cloudmesh/graphql

this way this integrates nice with other peoples code as needed for open source contribution

**Comment by laszewsk** [comment]
naturally change name in setup.py ...

**Comment by acatejr** [comment]
@laszewsk  Want to make sure I understand.

- [x] Within hid-sp18-505, I should create cloudmesh/graphql
- [x] All source code, but no requirements.txt
- [x] Adjust setup.py

https://gph.is/2AmePHo

**Comment by acatejr** [comment]
@laszewsk Found your example folder.  Thanks!!  Nice!!  :+1:
